workflows:
  android-workflow:
    name: KMM Android Workflow
    max_build_duration: 120
    environment:
      java: 17
      android_signing:
        - testKeystore
      groups:
        - google_credentials3
      vars:
        PACKAGE_NAME: "io.codemagic.dtrdic17"
        GOOGLE_PLAY_TRACK: alpha
    scripts:
      - name: Build Android release
        script: | 
         # cd $CM_BUILD_DIR
          ./gradlew bundleRelease \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=1.0.$BUILD_NUMBER
    artifacts:
      - androidApp/build/outputs/**/**/*.aab
    publishing:
      email:
        recipients:
          - david@nevercode.io
        notify:
          success: true
          failure: false
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal
      #   submit_as_draft: true

  ios-workflow:
    name: KMM iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: DavidAPIkey
    environment:
      xcode: 15
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.codemagic.kmmsample.dtrdic
      vars:
        APP_STORE_APPLE_ID: 6477870575
        XCODE_WORKSPACE: "iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"
    scripts:
      - name: Cocoapods installation
        script: | 
          cd $CM_BUILD_DIR/iosApp
          pod install
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Increment build number
        script: | 
          cd $CM_BUILD_DIR/iosApp
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: | 
          cd $CM_BUILD_DIR/iosApp
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - iosApp/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - david@nevercode.io
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration