workflows:
  android-workflow:
    name: KMM Android Workflow
    max_build_duration: 120
    environment:
      android_signing:
        - testKeystore
      groups:
        - google_credentials3
      vars:
        PACKAGE_NAME: "io.codemagic.dtrdic17"
        GOOGLE_PLAY_TRACK: alpha
    scripts:
      - name: Build Android release
        script: | 
          cd $CM_BUILD_DIR
          ./gradlew bundleRelease \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=1.0.$BUILD_NUMBER
    artifacts:
      - androidApp/build/outputs/**/**/*.aab
    publishing:
      email:
        recipients:
          - david@nevercode.io
        notify:
          success: true
          failure: false
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal
      #   submit_as_draft: true